[View in Colaboratory](https://colab.research.google.com/github/igrosny/deep_learning_book/blob/master/Capitulo_2_Algebra_Lineal.ipynb)

# 2 Algebra Lineal
## 2.1 Escalares, Vectores , Matrices y Tensores

**Escalar: ** Un escalar es solo un numero.

**Vector: ** Es un arreglo de numeros. A continuacion muestro un vector columna

$x = \begin{bmatrix}x_{1} \\ x_{2} \\ \vdots \\x_{m}\end{bmatrix}$

En el siguiente ejemplo lo vamos a representar en python

$x = \begin{bmatrix}2 \\ 3 \\ 7 \\8\end{bmatrix}$

In [3]:
import numpy as np

x = np.array([2,3,7,8])

print(x)

[2 3 7 8]


** Matrices: ** Es un arreglo de dos dimensiones donde cada elemento se puede identificar por dos indices. m: filas y n: columnas

$\begin{bmatrix}A_{1,1} & A_{1,2}\\ A_{2,1} & A_{2,2} \end{bmatrix}$

En el siguiente ejemplo voy a construir la siguiente matriz a python

$\begin{bmatrix}1 & 2\\3&4 \end{bmatrix}$

In [14]:
x = np.array([[1,2,6],[3,4,7],[0,5,9]])

print(x)

print("Imprimir primera fila: \n", x[0])
print("Imprimir todo despues de la primer fila: \n", x[1:])
print("Imprimir el elemento 2, 2: \n", x[1][1])

[[1 2 6]
 [3 4 7]
 [0 5 9]]
Imprimir primera fila: 
 [1 2 6]
Imprimir todo despues de la primer fila: 
 [[3 4 7]
 [0 5 9]]
Imprimir el elemento 2, 2: 
 4


La transpuesta de una matriz son todo los el

In [15]:
x.T

array([[1, 3, 0],
       [2, 4, 5],
       [6, 7, 9]])