[View in Colaboratory](https://colab.research.google.com/github/igrosny/deep_learning_book/blob/master/Capitulo_2_Algebra_Lineal.ipynb)

# 2 Algebra Lineal
## 2.1 Escalares, Vectores , Matrices y Tensores

**Escalar: ** Un escalar es solo un numero.

**Vector: ** Es un arreglo de numeros. A continuacion muestro un vector columna

$x = \begin{bmatrix}x_{1} \\ x_{2} \\ \vdots \\x_{m}\end{bmatrix}$

En el siguiente ejemplo lo vamos a representar en python

$x = \begin{bmatrix}2 \\ 3 \\ 7 \\8\end{bmatrix}$

In [2]:
import numpy as np

x = np.array([2,3,7,8])

print(x)

[2 3 7 8]


** Matrices: ** Es un arreglo de dos dimensiones donde cada elemento se puede identificar por dos indices. m: filas y n: columnas

$\begin{bmatrix}A_{1,1} & A_{1,2}\\ A_{2,1} & A_{2,2} \end{bmatrix}$

En el siguiente ejemplo voy a construir la siguiente matriz a python

$\begin{bmatrix}1 & 2\\3&4 \end{bmatrix}$

In [3]:
x = np.array([[1,2,6],[3,4,7],[0,5,9]])

print(x)

print("Imprimir primera fila: \n", x[0])
print("Imprimir todo despues de la primer fila: \n", x[1:])
print("Imprimir el elemento 2, 2: \n", x[1][1])

[[1 2 6]
 [3 4 7]
 [0 5 9]]
Imprimir primera fila: 
 [1 2 6]
Imprimir todo despues de la primer fila: 
 [[3 4 7]
 [0 5 9]]
Imprimir el elemento 2, 2: 
 4


La transpuesta de una matriz son todo los el

In [4]:
x.T

array([[1, 3, 0],
       [2, 4, 5],
       [6, 7, 9]])

## 2.2 Multiplicando matrices y vectores

$C=AB$

A tiene que ser m x n, B sera n x p y C va a quedar como m x p

El producto entre dos matrices se define como:

$C_{i,j} = \sum_kA_{i,k}B_{k,j}$

In [13]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

# Estas son las dos formas de multiplicar entre matrices
# np.dot(a,  b)
np.matmul(b, [1,1])

array([5, 4])

**Producto Hadamard** es el producto de los elementos individuales $C_{ij} = A_{ij}B_{ij}$

In [14]:
np.multiply(a,b)

array([[4, 0],
       [0, 2]])

Las propiedades del producto son:
* Es distributivo $A(B+C) = AB+AC$
* Es asociativo $A(BC) = (AB)C$
* **NO** es conmutativo: $AB = BA$ No aplica en todos lo casos
* La traspuesta de una matriz producto es: $(AB)^T = B^TA^T$


## 2.3 Matriz Identidad e Inversa

La matriz identidad es una matriz que no cambia ningun vector cuando la multiplicamos por esa matriz

$\forall x \in R^n, I_nx=x$

Es un matriz con unos en la diagonal

$\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}$

La matriz inversa es tal que multiplicada por la matriz original, te da la identidad

$A^{-1}A=I_n$

No siempre se puede encontrar la inversa de una matriz

In [15]:
# Crea una matriz identidad de dim 3

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Calculas la inversa de una matriz (tiene que ser cuadrada)
a = np.array([[1., 2.], [3., 4.]])

np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 2.4 Dependencia Lineal y Sistema generador

Un sistemas de ecuaciones $Ax = b$ puede tener solucion unica, no tener solucion o tener infinitas soluciones. Lo que no puede pasar es que tenga mas de una solucion pero menos de infinitas.

**Span** de un conjunto de vectores es el conjunto de todos los puntos obtenidos por la combinacion lineal de los vectores originales. (Ej: span(a, b) = R2)

$\bar a=\begin{bmatrix}1\\2\end{bmatrix}$   $\bar b=\begin{bmatrix}0\\3\end{bmatrix}$

$c_1 \bar a + c_2 \bar b = \bar c$

$c_1 \begin{bmatrix}1\\2\end{bmatrix} + c_2 \begin{bmatrix}0\\3\end{bmatrix} = \begin{bmatrix}x_1\\x_2\end{bmatrix}$

$1c_1 + 0c_2 = x_1$

$2c_1 + 3c_2 = x_2$

Resolvemos y queda:

$c_1 = x_1$

$c_2 = \frac{1}{3}(x_2 - 2x_1)$

Por eso decimos que esos vectores generan todo $R^2$
